# vim:set noexpandtab:

#
# This file is part of the '{{$directory}}' package.
#
# (c) {{$author}} <{{$email}}>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

#**
# Makefile for {{$directory}}.
#
# @octdoc       h:{{$module}}/Makefile
# @copyright    copyright (c) {{$year}} by {{$company}}
# @author       {{$author}} <{{$email}}>
#**

include ../org.octris.core/Makefile.cli

project = "{{$directory}}"
