# vim:set noexpandtab:

#**
# Makefile for {{$directory}}.
#
# @octdoc       h:./Makefile
# @copyright    copyright (c) {{$year}} by {{$company}}
# @author       {{$author}} <{{$email}}>
#**

include ../org.octris.core/Makefile.core

project = "{{$directory}}"
